folia: fix: run NetworkRootReadyEvent not async
because from folia 1.21.6, when this event not in async will cause a lot of warming of NetworkRootReadyEvent

I can't find full running link to specific this event run async. logs not tell me that

and there's async not work, when it runs TickerTask, it will be run sync with location as "Slimefun.runSyncAtLocation"

[22:01:13] [Region Scheduler Thread #1/WARN]: [Slimefun] Location task for Slimefun v6b0f3fc-Insider in world CraftWorld{name=world} at 585, -155 generated an exception
java.lang.IllegalStateException: NetworkRootReadyEvent may only be triggered asynchronously.
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:40) ~[folia-1.21.6.jar:1.21.6-DEV-3ef3a4e]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[folia-1.21.6.jar:1.21.6-DEV-3ef3a4e]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[folia-api-1.21.6-R0.1-SNAPSHOT.jar:?]
	at NetworksExpansion vSpecial-Version-36.jar/io.github.sefiraat.networks.slimefun.network.NetworkController$1.tick(NetworkController.java:91) ~[NetworksExpansion vSpecial-Version-36.jar:?]
	at Slimefun-6b0f3fc-Insider.jar/io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.lambda$tickBlock$6(TickerTask.java:243) ~[Slimefun-6b0f3fc-Insider.jar:?]
	at Slimefun-6b0f3fc-Insider.jar/io.github.thebusybiscuit.slimefun4.libraries.folialib.impl.FoliaImplementation.lambda$runAtLocationLater$11(FoliaImplementation.java:255) ~[Slimefun-6b0f3fc-Insider.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaRegionScheduler$LocationScheduledTask.run(FoliaRegionScheduler.java:331) ~[folia-1.21.6.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaRegionScheduler$Scheduler.tick(FoliaRegionScheduler.java:272) ~[folia-1.21.6.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaRegionScheduler.tick(FoliaRegionScheduler.java:142) ~[folia-1.21.6.jar:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1646) ~[folia-1.21.6.jar:1.21.6-DEV-3ef3a4e]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.21.6.jar:1.21.6-DEV-3ef3a4e]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:418) ~[folia-1.21.6.jar:1.21.6-DEV-3ef3a4e]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:546) ~[concurrentutil-0.0.3.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]